//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoansWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLoan()
        {
            this.tblUserLoans = new HashSet<tblUserLoan>();
        }
    
        public long tbLoanId { get; set; }
        public long ActualLoanid { get; set; }
        public long primaryBorowerID { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime modifiedAt { get; set; }
        public int tblStatusID { get; set; }
        public bool isActive { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblLoanStatu tblLoanStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserLoan> tblUserLoans { get; set; }
    }
}
