//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoansWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserAlert
    {
        public long tbUserID { get; set; }
        public int tbAlertID { get; set; }
        public bool isRead { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual tblAlert tblAlert { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
